[workspace]

members = [
    "auxin",
    "auxin_cli",
    "auxin_protos",
]

[patch.crates-io]
curve25519-dalek = { version = "3.0.0", git = "https://github.com/signalapp/curve25519-dalek.git", branch = "lizard2"}