# fly.toml file generated for auxin-cli on 2021-10-18T16:02:30-04:00

app = "auxin-echobot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

# flyctl volumes create auxin_echobot_state --region iad --size 10
[[mounts]]
  source = "auxin_echobot_state"
  destination = "/auxin_state"
