[package]
name = "auxin-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
auxin_protos = { path = "../auxin_protos" }
auxin = { path = "../auxin" }

uuid = {version="0.8.2", features=["serde", "v4"]}

simple_logger = "1.11.0"
log = "0.4.14"

serde = {version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"