[package]
name = "auxin-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
auxin_protos = { path = "../auxin_protos" }
auxin = { path = "../auxin" }

uuid = {version="0.8.2", features=["serde", "v4"]}

simple_logger = "1.11.0"
log = "0.4.14"

serde = {version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
base64 = "0.13"
futures = "0.3.15"
custom_error = "1.9.2"
libsignal-protocol = { git = "https://github.com/signalapp/libsignal-client", version = "0.1.0" }
rand = "0.7.3"

tokio-native-tls = "0.3.0"
tokio = { version = "1.6.1", features = ["full"] }
tokio-tungstenite = { version = "0.14.0", features = ["native-tls",] }
tungstenite = { version = "0.13.0", features = ["native-tls"]}
hyper = { version = "0.14.9", features = ["full"] }
hyper-tls = "0.5.0"

clap = "2.33.3"

http = "0.2.4"
httparse = "1.4.1"

protobuf = "2.24.1"

x509-parser = "0.9.2"
aes-gcm =  {version="0.9.2", features=["std"]}
x25519-dalek = "1.1.1"
async-trait = "0.1.50"
lazy_static = "1.4.0"