on: [push]

name: build
jobs:
  check:
    name: auxin-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
#      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: auxin-cli
          path: target/release/auxin-cli
#      - name: Run test of build against echoserver
#        run: /bin/sh -c './test_echobot.sh'
